O Numpy é uma biblioteca de algebra Linear em Python. A razão de sua importancia vem do fato de que praticamente todas as bibliotecas de ecossistemas PyData dependem do NumPy. Além disso, ele é incrivelmente rapido, pois tem conexões com bibliotecas em C.

## NumPy Arrays

Numpy arrays aparecem em duas formas: vetores ematrizes. Vetores são estranhamente arrays 1-D e matrizes são 2-D  (porem, uma matriz pode, eventulment, conter apenas uma coluna ou uma linha)

#### Utilizando o NumPy

In [ ]:
import numpy as np


### De uma lista

Pode-se criar uma array convertendo diretamente uma lista ou listas de listas

In [ ]:
my_list = [1, 2, 3]
print(my_list)

[2, 3]


In [ ]:
np.array(my_list)

array([2, 3])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6,], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Métodos de construção interna

Existem varios métodos de iternos para gerar arrays

#### Arrange


Retorna valores separados igualmente em um dado intervalo

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### Zeros e ones

Gera arrays de zeros e uns

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Linspace

Retorna números igualmente espaçados em um intervalo específico

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye

Cria uma matrix identidade

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Ramdom
O numpy possui várias formas de criar arrays de números aleatórios

#### rad
Cria uma array na forma dada e popula ela com amostras aleaórias de uma distribuição uniforme entre [0,1)

o [ significa que o número pertence ao grupo
e o ) número não pode acontecer

In [ ]:
np.random.rand(2)

array([0.60679188, 0.39479796])

In [ ]:
np.random.rand(5,5)

array([[0.91460949, 0.84723557, 0.97326436, 0.96646548, 0.47471469],
       [0.38656922, 0.88556972, 0.40773262, 0.15449817, 0.09731872],
       [0.39200418, 0.02848331, 0.23314519, 0.77399361, 0.37764997],
       [0.57983628, 0.27098626, 0.86078327, 0.74141236, 0.93672364],
       [0.62354794, 0.99740569, 0.61288439, 0.22869363, 0.10215676]])

#### randn
Retorna uma amostra (ou amostras) de uma "distribuição normal padrão". Diferente do rand, que é uniforme

In [ ]:
np.random.rand(2)

array([0.63139332, 0.14430545])

In [ ]:
np.random.randn(5,5)

array([[-0.44290016, -0.15191589, -0.48407696, -0.4302841 ,  2.25563753],
       [ 0.09817882,  0.6438803 , -2.46324239,  0.61947659, -0.99342832],
       [ 0.15726854,  0.88821154, -1.7906144 ,  0.49224188, -0.18131617],
       [ 0.23944408, -1.22651249, -0.46941001,  1.21200346, -0.48931826],
       [-0.31442338, -0.18605079, -0.64914256, -0.12064067,  1.99009753]])

#### radnt
Retorna um interiro entre low (inclusive) e high (exclusivo)

In [ ]:
np.random.randint(1,100)

72

In [ ]:
np.random.randint(1,100,200)

array([44, 52,  9, 32,  4, 48, 88, 15, 82, 24, 78, 87, 94, 10, 66,  5, 61,
        7,  9, 99, 89, 28, 19, 58, 98, 78, 90, 60, 25, 82, 72, 25, 66, 54,
       81, 42, 38, 99, 88,  9,  9, 40, 23, 57, 36, 56, 47, 64, 78, 74, 76,
       74, 48, 52, 25, 70, 17, 47, 28, 84, 71, 99, 43, 54, 83, 27, 49, 39,
       67, 34, 24, 96, 72,  7, 34, 35, 76, 35, 66, 32, 81, 42, 76, 10, 69,
       37,  2, 13, 82, 67, 25, 94, 52, 17,  5, 83, 90, 75, 73, 75, 95, 11,
       99, 95, 95, 62, 26, 20, 88, 94, 32, 65, 13, 87,  2, 32, 25, 82,  5,
       21, 29, 25, 66, 10, 97, 55, 65, 17, 46, 24, 94, 17, 59, 65, 49, 52,
       91, 78, 44, 71, 22, 95, 66, 55, 68, 56, 19,  8, 22, 17,  2, 41, 47,
       32, 18, 55, 42,  8, 55, 92, 81, 70, 78,  6, 12, 72, 59,  3, 84,  2,
       19, 60, 43, 16, 26, 97, 37, 11, 78, 30, 30, 93, 95,  4, 19, 10, 24,
       89, 35, 61, 85, 79, 36, 96, 87, 33, 10, 44, 55, 76])

### Atributos e métodos das Arrays
Vamos discutir alguns atributos e métodos úteis de uma array

In [ ]:
arr = np.arange(25)
print(arr)
ranarr = np.random.randint(0,50,10)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[37 20  4  2  6 15 26 23 25 30]


### Reshape
Retorna uma array contendo a mesma informação com uma nova forma

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Max, min, argmax, armin
Estes são métodos úteis para encontrar valores maximos ou minimos. Ou para encontrar seu índice de localizção utilizando argmin ou argmax

In [ ]:
ranarr.max()

37

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

3

#### Shape
Shape é um atributo que as arrays possuem (não é um método)

In [ ]:
arr.shape

(25,)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

#### dtype
Também possível obter o tipo de dado dos objetos de uma array

In [ ]:
arr.dtype

dtype('int64')

#### Indexação e seleção
Iremos discutir agora como selecionar elementos ou grupos de elementos de um array

In [ ]:
arr = np.arrange(0,11)
print(arr)

### Indexação e seleção com colchetes
A maneira mais simples para obter algum elemento de uma array é similar ao que se faz com as listas

In [ ]:
arr[8]

8

In [ ]:
arr[2:5]

array([2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting
As arrays do numpy diferem de uma lista normal do python por sua capacidade de broadcast

In [ ]:
print(arr)
arr[:5] = 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [ ]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
slice_of_arr = arr[0:5]
print(slice_of_arr)

[0 1 2 3 4]


In [ ]:
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99 99]


In [ ]:
print(arr)

[99 99 99 99 99  5  6  7  8  9 10]


In [ ]:
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99  5  6  7  8  9 10]


#### Indexadando uma array 2D (matrizes)
O formato geral é arr_2d[row][col] ou arr_2d[row,col]

In [ ]:
arr_2d = np.array([[5,10,25], [20,25,30], [35,40,45]])
print(arr_2d)

[[ 5 10 25]
 [20 25 30]
 [35 40 45]]


In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 25],
       [25, 30]])

In [ ]:
arr_2d[:,2]

array([25, 30, 45])

#### Operações aritiméticas no numpy


In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-60-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

<ipython-input-61-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Funções Universais

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr)

<ipython-input-69-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])